-- 0002_seed_brands.sql
-- Seed data for the brands table for the logo quiz.

INSERT INTO brands (brand_name, difficulty, country, logo, hidden_logo) VALUES
('abarth', 5, 'Italy', '/assets/images/brands/abarth/logos/abarth-logo', '/assets/images/brands/abarth/logos/abarth-logo-hidden'),
('acura', 3, 'Japan', '/assets/images/brands/acura/logos/acura-logo', '/assets/images/brands/acura/logos/acura-logo-hidden'),
('aiways', 4, 'China', '/assets/images/brands/aiways/logos/aiways-logo', '/assets/images/brands/aiways/logos/aiways-logo-hidden'),
('aixam', 2, 'France', '/assets/images/brands/aixam/logos/aixam-logo', '/assets/images/brands/aixam/logos/aixam-logo-hidden'),
('alfa_romeo', 3, 'Italy', '/assets/images/brands/alfa_romeo/logos/alfa_romeo-logo', '/assets/images/brands/alfa_romeo/logos/alfa_romeo-logo-hidden'),
('alpine', 4, 'France', '/assets/images/brands/alpine/logos/alpine-logo', '/assets/images/brands/alpine/logos/alpine-logo-hidden'),
('apollo', 5, 'Germany', '/assets/images/brands/apollo/logos/apollo-logo', '/assets/images/brands/apollo/logos/apollo-logo-hidden'),
('ariel', 4, 'United Kingdom', '/assets/images/brands/ariel/logos/ariel-logo', '/assets/images/brands/ariel/logos/ariel-logo-hidden'),
('aspark', 5, 'Japan', '/assets/images/brands/aspark/logos/aspark-logo', '/assets/images/brands/aspark/logos/aspark-logo-hidden'),
('aston_martin', 3, 'United Kingdom', '/assets/images/brands/aston_martin/logos/aston_martin-logo', '/assets/images/brands/aston_martin/logos/aston_martin-logo-hidden'),
('audi', 1, 'Germany', '/assets/images/brands/audi/logos/audi-logo', '/assets/images/brands/audi/logos/audi-logo-hidden'),
('bac', 5, 'United Kingdom', '/assets/images/brands/bac/logos/bac-logo', '/assets/images/brands/bac/logos/bac-logo-hidden'),
('bentley', 2, 'United Kingdom', '/assets/images/brands/bentley/logos/bentley-logo', '/assets/images/brands/bentley/logos/bentley-logo-hidden'),
('bmw', 1, 'Germany', '/assets/images/brands/bmw/logos/bmw-logo', '/assets/images/brands/bmw/logos/bmw-logo-hidden'),
('bugatti', 5, 'France', '/assets/images/brands/bugatti/logos/bugatti-logo', '/assets/images/brands/bugatti/logos/bugatti-logo-hidden'),
('buick', 3, 'United States', '/assets/images/brands/buick/logos/buick-logo', '/assets/images/brands/buick/logos/buick-logo-hidden'),
('cadillac', 2, 'United States', '/assets/images/brands/cadillac/logos/cadillac-logo', '/assets/images/brands/cadillac/logos/cadillac-logo-hidden'),
('caterham', 4, 'United Kingdom', '/assets/images/brands/caterham/logos/caterham-logo', '/assets/images/brands/caterham/logos/caterham-logo-hidden'),
('chevrolet', 1, 'United States', '/assets/images/brands/chevrolet/logos/chevrolet-logo', '/assets/images/brands/chevrolet/logos/chevrolet-logo-hidden'),
('chevrolet_corvette', 2, 'United States', '/assets/images/brands/chevrolet_corvette/logos/chevrolet_corvette-logo', '/assets/images/brands/chevrolet_corvette/logos/chevrolet_corvette-logo-hidden'),
('citroën', 3, 'France', '/assets/images/brands/citroën/logos/citroën-logo', '/assets/images/brands/citroën/logos/citroën-logo-hidden'),
('dacia', 2, 'Romania', '/assets/images/brands/dacia/logos/dacia-logo', '/assets/images/brands/dacia/logos/dacia-logo-hidden'),
('dmc', 5, 'United States', '/assets/images/brands/dmc/logos/dmc-logo', '/assets/images/brands/dmc/logos/dmc-logo-hidden'),
('dodge', 2, 'United States', '/assets/images/brands/dodge/logos/dodge-logo', '/assets/images/brands/dodge/logos/dodge-logo-hidden'),
('donkervoort', 5, 'Netherlands', '/assets/images/brands/donkervoort/logos/donkervoort-logo', '/assets/images/brands/donkervoort/logos/donkervoort-logo-hidden'),
('drako', 5, 'United States', '/assets/images/brands/drako/logos/drako-logo', '/assets/images/brands/drako/logos/drako-logo-hidden'),
('elemental', 4, 'United Kingdom', '/assets/images/brands/elemental/logos/elemental-logo', '/assets/images/brands/elemental/logos/elemental-logo-hidden'),
('ferrari', 2, 'Italy', '/assets/images/brands/ferrari/logos/ferrari-logo', '/assets/images/brands/ferrari/logos/ferrari-logo-hidden'),
('fiat', 2, 'Italy', '/assets/images/brands/fiat/logos/fiat-logo', '/assets/images/brands/fiat/logos/fiat-logo-hidden'),
('ford', 1, 'United States', '/assets/images/brands/ford/logos/ford-logo', '/assets/images/brands/ford/logos/ford-logo-hidden'),
('geely', 4, 'China', '/assets/images/brands/geely/logos/geely-logo', '/assets/images/brands/geely/logos/geely-logo-hidden'),
('genesis', 3, 'South Korea', '/assets/images/brands/genesis/logos/genesis-logo', '/assets/images/brands/genesis/logos/genesis-logo-hidden'),
('ginetta', 4, 'United Kingdom', '/assets/images/brands/ginetta/logos/ginetta-logo', '/assets/images/brands/ginetta/logos/ginetta-logo-hidden'),
('great_wall', 3, 'China', '/assets/images/brands/great_wall/logos/great_wall-logo', '/assets/images/brands/great_wall/logos/great_wall-logo-hidden'),
('honda', 1, 'Japan', '/assets/images/brands/honda/logos/honda-logo', '/assets/images/brands/honda/logos/honda-logo-hidden'),
('hyundai', 1, 'South Korea', '/assets/images/brands/hyundai/logos/hyundai-logo', '/assets/images/brands/hyundai/logos/hyundai-logo-hidden'),
('ikco', 4, 'Iran', '/assets/images/brands/ikco/logos/ikco-logo', '/assets/images/brands/ikco/logos/ikco-logo-hidden'),
('infiniti', 3, 'Japan', '/assets/images/brands/infiniti/logos/infiniti-logo', '/assets/images/brands/infiniti/logos/infiniti-logo-hidden'),
('jaguar', 2, 'United Kingdom', '/assets/images/brands/jaguar/logos/jaguar-logo', '/assets/images/brands/jaguar/logos/jaguar-logo-hidden'),
('karlmann_king', 5, 'Germany', '/assets/images/brands/karlmann_king/logos/karlmann_king-logo', '/assets/images/brands/karlmann_king/logos/karlmann_king-logo-hidden'),
('kia', 1, 'South Korea', '/assets/images/brands/kia/logos/kia-logo', '/assets/images/brands/kia/logos/kia-logo-hidden'),
('koenigsegg', 5, 'Sweden', '/assets/images/brands/koenigsegg/logos/koenigsegg-logo', '/assets/images/brands/koenigsegg/logos/koenigsegg-logo-hidden'),
('lada', 4, 'Russia', '/assets/images/brands/lada/logos/lada-logo', '/assets/images/brands/lada/logos/lada-logo-hidden'),
('lamborghini', 3, 'Italy', '/assets/images/brands/lamborghini/logos/lamborghini-logo', '/assets/images/brands/lamborghini/logos/lamborghini-logo-hidden'),
('lancia', 3, 'Italy', '/assets/images/brands/lancia/logos/lancia-logo', '/assets/images/brands/lancia/logos/lancia-logo-hidden'),
('land_rover', 2, 'United Kingdom', '/assets/images/brands/land_rover/logos/land_rover-logo', '/assets/images/brands/land_rover/logos/land_rover-logo-hidden'),
('levc', 2, 'United Kingdom', '/assets/images/brands/levc/logos/levc-logo', '/assets/images/brands/levc/logos/levc-logo-hidden'),
('lexus', 2, 'Japan', '/assets/images/brands/lexus/logos/lexus-logo', '/assets/images/brands/lexus/logos/lexus-logo-hidden'),
('lincoln', 2, 'United States', '/assets/images/brands/lincoln/logos/lincoln-logo', '/assets/images/brands/lincoln/logos/lincoln-logo-hidden'),
('li_auto', 3, 'China', '/assets/images/brands/li_auto/logos/li_auto-logo', '/assets/images/brands/li_auto/logos/li_auto-logo-hidden'),
('lotus', 3, 'United Kingdom', '/assets/images/brands/lotus/logos/lotus-logo', '/assets/images/brands/lotus/logos/lotus-logo-hidden'),
('mahindra', 3, 'India', '/assets/images/brands/mahindra/logos/mahindra-logo', '/assets/images/brands/mahindra/logos/mahindra-logo-hidden'),
('maserati', 3, 'Italy', '/assets/images/brands/maserati/logos/maserati-logo', '/assets/images/brands/maserati/logos/maserati-logo-hidden'),
('mazda', 1, 'Japan', '/assets/images/brands/mazda/logos/mazda-logo', '/assets/images/brands/mazda/logos/mazda-logo-hidden'),
('mclaren', 5, 'United Kingdom', '/assets/images/brands/mclaren/logos/mclaren-logo', '/assets/images/brands/mclaren/logos/mclaren-logo-hidden'),
('mercedes-benz', 1, 'Germany', '/assets/images/brands/mercedes-benz/logos/mercedes-benz-logo', '/assets/images/brands/mercedes-benz/logos/mercedes-benz-logo-hidden'),
('mg', 3, 'United Kingdom', '/assets/images/brands/mg/logos/mg-logo', '/assets/images/brands/mg/logos/mg-logo-hidden'),
('mini', 2, 'United Kingdom', '/assets/images/brands/mini/logos/mini-logo', '/assets/images/brands/mini/logos/mini-logo-hidden'),
('mitsubishi', 2, 'Japan', '/assets/images/brands/mitsubishi/logos/mitsubishi-logo', '/assets/images/brands/mitsubishi/logos/mitsubishi-logo-hidden'),
('nio', 3, 'China', '/assets/images/brands/nio/logos/nio-logo', '/assets/images/brands/nio/logos/nio-logo-hidden'),
('nissan', 1, 'Japan', '/assets/images/brands/nissan/logos/nissan-logo', '/assets/images/brands/nissan/logos/nissan-logo-hidden'),
('opel', 2, 'Germany', '/assets/images/brands/opel/logos/opel-logo', '/assets/images/brands/opel/logos/opel-logo-hidden'),
('pagani', 5, 'Italy', '/assets/images/brands/pagani/logos/pagani-logo', '/assets/images/brands/pagani/logos/pagani-logo-hidden'),
('perodua', 3, 'Malaysia', '/assets/images/brands/perodua/logos/perodua-logo', '/assets/images/brands/perodua/logos/perodua-logo-hidden'),
('peugeot', 2, 'France', '/assets/images/brands/peugeot/logos/peugeot-logo', '/assets/images/brands/peugeot/logos/peugeot-logo-hidden'),
('polestar', 4, 'Sweden', '/assets/images/brands/polestar/logos/polestar-logo', '/assets/images/brands/polestar/logos/polestar-logo-hidden'),
('pontiac', 3, 'United States', '/assets/images/brands/pontiac/logos/pontiac-logo', '/assets/images/brands/pontiac/logos/pontiac-logo-hidden'),
('porsche', 1, 'Germany', '/assets/images/brands/porsche/logos/porsche-logo', '/assets/images/brands/porsche/logos/porsche-logo-hidden'),
('proton', 3, 'Malaysia', '/assets/images/brands/proton/logos/proton-logo', '/assets/images/brands/proton/logos/proton-logo-hidden'),
('renault', 2, 'France', '/assets/images/brands/renault/logos/renault-logo', '/assets/images/brands/renault/logos/renault-logo-hidden'),
('rivian', 4, 'United States', '/assets/images/brands/rivian/logos/rivian-logo', '/assets/images/brands/rivian/logos/rivian-logo-hidden'),
('rolls-royce', 2, 'United Kingdom', '/assets/images/brands/rolls-royce/logos/rolls-royce-logo', '/assets/images/brands/rolls-royce/logos/rolls-royce-logo-hidden'),
('saab', 4, 'Sweden', '/assets/images/brands/saab/logos/saab-logo', '/assets/images/brands/saab/logos/saab-logo-hidden'),
('seat', 2, 'Spain', '/assets/images/brands/seat/logos/seat-logo', '/assets/images/brands/seat/logos/seat-logo-hidden'),
('smart', 1, 'Germany', '/assets/images/brands/smart/logos/smart-logo', '/assets/images/brands/smart/logos/smart-logo-hidden'),
('ssc', 5, 'United States', '/assets/images/brands/ssc/logos/ssc-logo', '/assets/images/brands/ssc/logos/ssc-logo-hidden'),
('subaru', 1, 'Japan', '/assets/images/brands/subaru/logos/subaru-logo', '/assets/images/brands/subaru/logos/subaru-logo-hidden'),
('suzuki', 1, 'Japan', '/assets/images/brands/suzuki/logos/suzuki-logo', '/assets/images/brands/suzuki/logos/suzuki-logo-hidden'),
('tata', 3, 'India', '/assets/images/brands/tata/logos/tata-logo', '/assets/images/brands/tata/logos/tata-logo-hidden'),
('tesla', 1, 'United States', '/assets/images/brands/tesla/logos/tesla-logo', '/assets/images/brands/tesla/logos/tesla-logo-hidden'),
('toyota', 1, 'Japan', '/assets/images/brands/toyota/logos/toyota-logo', '/assets/images/brands/toyota/logos/toyota-logo-hidden'),
('vauxhall', 2, 'United Kingdom', '/assets/images/brands/vauxhall/logos/vauxhall-logo', '/assets/images/brands/vauxhall/logos/vauxhall-logo-hidden'),
('vinfast', 4, 'Vietnam', '/assets/images/brands/vinfast/logos/vinfast-logo', '/assets/images/brands/vinfast/logos/vinfast-logo-hidden'),
('volkswagen', 1, 'Germany', '/assets/images/brands/volkswagen/logos/volkswagen-logo', '/assets/images/brands/volkswagen/logos/volkswagen-logo-hidden'),
('volvo', 2, 'Sweden', '/assets/images/brands/volvo/logos/volvo-logo', '/assets/images/brands/volvo/logos/volvo-logo-hidden'),
('w_motors', 5, 'Lebanon', '/assets/images/brands/w_motors/logos/w_motors-logo', '/assets/images/brands/w_motors/logos/w_motors-logo-hidden'),
('xpeng', 4, 'China', '/assets/images/brands/xpeng/logos/xpeng-logo', '/assets/images/brands/xpeng/logos/xpeng-logo-hidden'),
('zenvo', 5, 'Denmark', '/assets/images/brands/zenvo/logos/zenvo-logo', '/assets/images/brands/zenvo/logos/zenvo-logo-hidden'),
('škoda', 1, 'Czech Republic', '/assets/images/brands/škoda/logos/škoda-logo', '/assets/images/brands/škoda/logos/škoda-logo-hidden');
