-- 0002_seed_brands.sql
-- Seed data for the logo quiz.

-- Seed data for the countries table.
INSERT INTO countries (id, country_name) VALUES
(1, 'Italy'),
(2, 'Japan'),
(3, 'China'),
(4, 'France'),
(5, 'Germany'),
(6, 'United Kingdom'),
(7, 'United States'),
(8, 'South Korea'),
(9, 'Netherlands'),
(10, 'Iran'),
(11, 'Russia'),
(12, 'Sweden'),
(13, 'Malaysia'),
(14, 'Czech Republic'),
(15, 'Spain'),
(16, 'Lebanon'),
(17, 'Vietnam');

-- Seed data for the brands table.
INSERT INTO brands (brand_name, difficulty, country_id, logo, hidden_logo) VALUES
('Abarth', 4, 1, '/assets/images/brands/abarth/logos/abarth-logo', '/assets/images/brands/abarth/logos/abarth-logo-hidden'),
('Acura', 4, 2, '/assets/images/brands/acura/logos/acura-logo', '/assets/images/brands/acura/logos/acura-logo-hidden'),
('Aiways', 5, 3, '/assets/images/brands/aiways/logos/aiways-logo', '/assets/images/brands/aiways/logos/aiways-logo-hidden'),
('Aixam', 4, 4, '/assets/images/brands/aixam/logos/aixam-logo', '/assets/images/brands/aixam/logos/aixam-logo-hidden'),
('Alfa Romeo', 3, 1, '/assets/images/brands/alfa_romeo/logos/alfa_romeo-logo', '/assets/images/brands/alfa_romeo/logos/alfa_romeo-logo-hidden'),
('Alpine', 5, 4, '/assets/images/brands/alpine/logos/alpine-logo', '/assets/images/brands/alpine/logos/alpine-logo-hidden'),
('Apollo', 5, 5, '/assets/images/brands/apollo/logos/apollo-logo', '/assets/images/brands/apollo/logos/apollo-logo-hidden'),
('Ariel', 5, 6, '/assets/images/brands/ariel/logos/ariel-logo', '/assets/images/brands/ariel/logos/ariel-logo-hidden'),
('Aspark', 5, 2, '/assets/images/brands/aspark/logos/aspark-logo', '/assets/images/brands/aspark/logos/aspark-logo-hidden'),
('Aston Martin', 2, 6, '/assets/images/brands/aston_martin/logos/aston_martin-logo', '/assets/images/brands/aston_martin/logos/aston_martin-logo-hidden'),
('Audi', 1, 5, '/assets/images/brands/audi/logos/audi-logo', '/assets/images/brands/audi/logos/audi-logo-hidden'),
('BAC', 5, 6, '/assets/images/brands/bac/logos/bac-logo', '/assets/images/brands/bac/logos/bac-logo-hidden'),
('Bentley', 3, 6, '/assets/images/brands/bentley/logos/bentley-logo', '/assets/images/brands/bentley/logos/bentley-logo-hidden'),
('BMW', 1, 5, '/assets/images/brands/bmw/logos/bmw-logo', '/assets/images/brands/bmw/logos/bmw-logo-hidden'),
('Bugatti', 2, 4, '/assets/images/brands/bugatti/logos/bugatti-logo', '/assets/images/brands/bugatti/logos/bugatti-logo-hidden'),
('Buick', 3, 7, '/assets/images/brands/buick/logos/buick-logo', '/assets/images/brands/buick/logos/buick-logo-hidden'),
('Cadillac', 1, 7, '/assets/images/brands/cadillac/logos/cadillac-logo', '/assets/images/brands/cadillac/logos/cadillac-logo-hidden'),
('Caterham', 5, 6, '/assets/images/brands/caterham/logos/caterham-logo', '/assets/images/brands/caterham/logos/caterham-logo-hidden'),
('Chevrolet', 1, 7, '/assets/images/brands/chevrolet/logos/chevrolet-logo', '/assets/images/brands/chevrolet/logos/chevrolet-logo-hidden'),
('Chevrolet Corvette', 3, 7, '/assets/images/brands/chevrolet_corvette/logos/chevrolet_corvette-logo', '/assets/images/brands/chevrolet_corvette/logos/chevrolet_corvette-logo-hidden'),
('Citroën', 2, 4, '/assets/images/brands/citroen/logos/citroen-logo', '/assets/images/brands/citroen/logos/citroen-logo-hidden'),
('Dacia', 4, 4, '/assets/images/brands/dacia/logos/dacia-logo', '/assets/images/brands/dacia/logos/dacia-logo-hidden'),
('Dodge', 2, 7, '/assets/images/brands/dodge/logos/dodge-logo', '/assets/images/brands/dodge/logos/dodge-logo-hidden'),
('Donkervoort', 5, 9, '/assets/images/brands/donkervoort/logos/donkervoort-logo', '/assets/images/brands/donkervoort/logos/donkervoort-logo-hidden'),
('Drako', 5, 7, '/assets/images/brands/drako/logos/drako-logo', '/assets/images/brands/drako/logos/drako-logo-hidden'),
('Elemental', 5, 6, '/assets/images/brands/elemental/logos/elemental-logo', '/assets/images/brands/elemental/logos/elemental-logo-hidden'),
('Ferrari', 1, 1, '/assets/images/brands/ferrari/logos/ferrari-logo', '/assets/images/brands/ferrari/logos/ferrari-logo-hidden'),
('Fiat', 3, 1, '/assets/images/brands/fiat/logos/fiat-logo', '/assets/images/brands/fiat/logos/fiat-logo-hidden'),
('Ford', 1, 7, '/assets/images/brands/ford/logos/ford-logo', '/assets/images/brands/ford/logos/ford-logo-hidden'),
('Geely', 4, 3, '/assets/images/brands/geely/logos/geely-logo', '/assets/images/brands/geely/logos/geely-logo-hidden'),
('Genesis', 4, 8, '/assets/images/brands/genesis/logos/genesis-logo', '/assets/images/brands/genesis/logos/genesis-logo-hidden'),
('Ginetta', 5, 6, '/assets/images/brands/ginetta/logos/ginetta-logo', '/assets/images/brands/ginetta/logos/ginetta-logo-hidden'),
('Great Wall Motor', 5, 3, '/assets/images/brands/great_wall/logos/great_wall-logo', '/assets/images/brands/great_wall/logos/great_wall-logo-hidden'),
('Honda', 1, 2, '/assets/images/brands/honda/logos/honda-logo', '/assets/images/brands/honda/logos/honda-logo-hidden'),
('Hyundai', 1, 8, '/assets/images/brands/hyundai/logos/hyundai-logo', '/assets/images/brands/hyundai/logos/hyundai-logo-hidden'),
('Iran Khodro', 5, 10, '/assets/images/brands/ikco/logos/ikco-logo', '/assets/images/brands/ikco/logos/ikco-logo-hidden'),
('Infiniti', 3, 2, '/assets/images/brands/infiniti/logos/infiniti-logo', '/assets/images/brands/infiniti/logos/infiniti-logo-hidden'),
('Jaguar', 2, 6, '/assets/images/brands/jaguar/logos/jaguar-logo', '/assets/images/brands/jaguar/logos/jaguar-logo-hidden'),
('Karlmann King', 5, 5, '/assets/images/brands/karlmann_king/logos/karlmann_king-logo', '/assets/images/brands/karlmann_king/logos/karlmann_king-logo-hidden'),
('Kia', 3, 8, '/assets/images/brands/kia/logos/kia-logo', '/assets/images/brands/kia/logos/kia-logo-hidden'),
('Koenigsegg', 3, 12, '/assets/images/brands/koenigsegg/logos/koenigsegg-logo', '/assets/images/brands/koenigsegg/logos/koenigsegg-logo-hidden'),
('Lada', 5, 11, '/assets/images/brands/lada/logos/lada-logo', '/assets/images/brands/lada/logos/lada-logo-hidden'),
('Lamborghini', 1, 1, '/assets/images/brands/lamborghini/logos/lamborghini-logo', '/assets/images/brands/lamborghini/logos/lamborghini-logo-hidden'),
('Lancia', 4, 1, '/assets/images/brands/lancia/logos/lancia-logo', '/assets/images/brands/lancia/logos/lancia-logo-hidden'),
('Land Rover', 3, 6, '/assets/images/brands/land_rover/logos/land_rover-logo', '/assets/images/brands/land_rover/logos/land_rover-logo-hidden'),
('London EV Company', 5, 6, '/assets/images/brands/levc/logos/levc-logo', '/assets/images/brands/levc/logos/levc-logo-hidden'),
('Lexus', 2, 2, '/assets/images/brands/lexus/logos/lexus-logo', '/assets/images/brands/lexus/logos/lexus-logo-hidden'),
('Lincoln', 3, 7, '/assets/images/brands/lincoln/logos/lincoln-logo', '/assets/images/brands/lincoln/logos/lincoln-logo-hidden'),
('Li Auto', 3, 3, '/assets/images/brands/li_auto/logos/liauto-logo', '/assets/images/brands/li_auto/logos/liauto-logo-hidden'),
('Lotus', 3, 6, '/assets/images/brands/lotus/logos/lotus-logo', '/assets/images/brands/lotus/logos/lotus-logo-hidden'),
('Mahindra', 4, 13, '/assets/images/brands/mahindra/logos/mahindra-logo', '/assets/images/brands/mahindra/logos/mahindra-logo-hidden'),
('Maserati', 2, 1, '/assets/images/brands/maserati/logos/maserati-logo', '/assets/images/brands/maserati/logos/maserati-logo-hidden'),
('Maybach', 4, 5, '/assets/images/brands/maybach/logos/maybach-logo', '/assets/images/brands/maybach/logos/maybach-logo-hidden'),
('Mazda', 1, 2, '/assets/images/brands/mazda/logos/mazda-logo', '/assets/images/brands/mazda/logos/mazda-logo-hidden'),
('Mclaren', 4, 6, '/assets/images/brands/mclaren/logos/mclaren-logo', '/assets/images/brands/mclaren/logos/mclaren-logo-hidden'),
('Mercedes-Benz', 1, 5, '/assets/images/brands/mercedes-benz/logos/mercedes-benz-logo', '/assets/images/brands/mercedes-benz/logos/mercedes-benz-logo-hidden'),
('MG', 4, 6, '/assets/images/brands/mg/logos/mg-logo', '/assets/images/brands/mg/logos/mg-logo-hidden'),
('Mini', 3, 6, '/assets/images/brands/mini/logos/mini-logo', '/assets/images/brands/mini/logos/mini-logo-hidden'),
('Mitsubishi', 2, 2, '/assets/images/brands/mitsubishi/logos/mitsubishi-logo', '/assets/images/brands/mitsubishi/logos/mitsubishi-logo-hidden'),
('Nio', 4, 3, '/assets/images/brands/nio/logos/nio-logo', '/assets/images/brands/nio/logos/nio-logo-hidden'),
('Nissan', 2, 2, '/assets/images/brands/nissan/logos/nissan-logo', '/assets/images/brands/nissan/logos/nissan-logo-hidden'),
('Opel', 2, 5, '/assets/images/brands/opel/logos/opel-logo', '/assets/images/brands/opel/logos/opel-logo-hidden'),
('Pagani', 4, 1, '/assets/images/brands/pagani/logos/pagani-logo', '/assets/images/brands/pagani/logos/pagani-logo-hidden'),
('Perodua', 5, 13, '/assets/images/brands/perodua/logos/perodua-logo', '/assets/images/brands/perodua/logos/perodua-logo-hidden'),
('Peugeot', 1, 4, '/assets/images/brands/peugeot/logos/peugeot-logo', '/assets/images/brands/peugeot/logos/peugeot-logo-hidden'),
('Polestar', 4, 12, '/assets/images/brands/polestar/logos/polestar-logo', '/assets/images/brands/polestar/logos/polestar-logo-hidden'),
('Pontiac', 3, 7, '/assets/images/brands/pontiac/logos/pontiac-logo', '/assets/images/brands/pontiac/logos/pontiac-logo-hidden'),
('Porsche', 1, 5, '/assets/images/brands/porsche/logos/porsche-logo', '/assets/images/brands/porsche/logos/porsche-logo-hidden'),
('Proton', 4, 13, '/assets/images/brands/proton/logos/proton-logo', '/assets/images/brands/proton/logos/proton-logo-hidden'),
('Renault', 1, 4, '/assets/images/brands/renault/logos/renault-logo', '/assets/images/brands/renault/logos/renault-logo-hidden'),
('Rivian', 4, 7, '/assets/images/brands/rivian/logos/rivian-logo', '/assets/images/brands/rivian/logos/rivian-logo-hidden'),
('Rolls Royce', 1, 6, '/assets/images/brands/rolls-royce/logos/rolls-royce-logo', '/assets/images/brands/rolls-royce/logos/rolls-royce-logo-hidden'),
('Saab', 2, 12, '/assets/images/brands/saab/logos/saab-logo', '/assets/images/brands/saab/logos/saab-logo-hidden'),
('SEAT', 2, 15, '/assets/images/brands/seat/logos/seat-logo', '/assets/images/brands/seat/logos/seat-logo-hidden'),
('Skoda', 3, 14, '/assets/images/brands/skoda/logos/skoda-logo', '/assets/images/brands/skoda/logos/skoda-logo-hidden'),
('Smart', 2, 5, '/assets/images/brands/smart/logos/smart-logo', '/assets/images/brands/smart/logos/smart-logo-hidden'),
('SSC North America', 5, 7, '/assets/images/brands/ssc/logos/ssc-logo', '/assets/images/brands/ssc/logos/ssc-logo-hidden'),
('Subaru', 2, 2, '/assets/images/brands/subaru/logos/subaru-logo', '/assets/images/brands/subaru/logos/subaru-logo-hidden'),
('Suzuki', 2, 2, '/assets/images/brands/suzuki/logos/suzuki-logo', '/assets/images/brands/suzuki/logos/suzuki-logo-hidden'),
('Tata', 4, 13, '/assets/images/brands/tata/logos/tata-logo', '/assets/images/brands/tata/logos/tata-logo-hidden'),
('Tesla', 1, 7, '/assets/images/brands/tesla/logos/tesla-logo', '/assets/images/brands/tesla/logos/tesla-logo-hidden'),
('Toyota', 1, 2, '/assets/images/brands/toyota/logos/toyota-logo', '/assets/images/brands/toyota/logos/toyota-logo-hidden'),
('Vauxhall', 3, 6, '/assets/images/brands/vauxhall/logos/vauxhall-logo', '/assets/images/brands/vauxhall/logos/vauxhall-logo-hidden'),
('Vinfast', 5, 17, '/assets/images/brands/vinfast/logos/vinfast-logo', '/assets/images/brands/vinfast/logos/vinfast-logo-hidden'),
('Volkswagen', 1, 5, '/assets/images/brands/volkswagen/logos/volkswagen-logo', '/assets/images/brands/volkswagen/logos/volkswagen-logo-hidden'),
('Volvo', 2, 12, '/assets/images/brands/volvo/logos/volvo-logo', '/assets/images/brands/volvo/logos/volvo-logo-hidden'),
('W Motors', 5, 16, '/assets/images/brands/w_motors/logos/w_motors-logo', '/assets/images/brands/w_motors/logos/w_motors-logo-hidden'),
('XPeng', 4, 3, '/assets/images/brands/xpeng/logos/xpeng-logo', '/assets/images/brands/xpeng/logos/xpeng-logo-hidden');
