name: 'CI - Car Logo Quiz'

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  unit-tests:
    name: 'Run Unit Tests'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Common Setup
        uses: ./.github/actions/common-setup
        with:
          node-version: '20'
      - name: Run Unit Tests
        run: npm run test:unit
        shell: bash

  acceptance-tests:
    name: 'Run Acceptance Tests'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Common Setup
        uses: ./.github/actions/common-setup
        with:
          node-version: '20'
      - name: Run Acceptance Tests
        run: npm run test:acceptance
        shell: bash
